language: c

compiler:
    - gcc

install:
    - git clone -b release_0.1 git://github.com/nardinan/miranda
    - echo $(cd miranda && mkdir build && cd build && cmake .. && make && sudo make install)

script:
    - make
